/// Flutter icons MyIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcon
///      fonts:
///       - asset: fonts/MyIcon.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcon {
  MyIcon._();

  static const _kFontFam = 'MyIcon';

  static const IconData search = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData picture = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData library_books_outline = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData event_note_outline = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData plus_square = const IconData(0xf196, fontFamily: _kFontFam);
  static const IconData chart_line = const IconData(0xf201, fontFamily: _kFontFam);
}
